name: Node.js CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        working-directory: app
        run: yarn

      - name: Build
        working-directory: app
        run: yarn build

      - name: Start
        working-directory: app
        run: yarn start
  
  build-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node.version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      
      - name: Install
        working-directory: api
        run: yarn

      - name: Build
        working-directory: api
        run: yarn build

      - name: Start
        working-directory: api
        run: yarn start

